dataset_collection = {
    "vtab": [
        "caltech101",
        "cifar100",
        "clevr_count_all",
        "clevr_closest_object_distance",
        "diabetic_retinopathy",
        "dmlab",
        "dsprites_label_orientation",
        "dsprites_label_x_position",
        "dtd",
        "eurosat",
        "kitti_closest_vehicle_distance",
        "flowers",
        "pets",
        "pcam",
        "resisc45",
        "smallnorb_label_azimuth",
        "smallnorb_label_elevation",
        "sun397",
        "svhn",
    ],
    "vtab+": [
        "imagenet1k",
        "imagenetv2",
        "imagenet_sketch",
        "imagenet-a",
        "imagenet-r",
        "objectnet",
        "fer2013",
        "voc2007",
        "voc2007_multilabel",
        "sun397",
        "stanfordcars",
        "fgvc_aircraft",
        "mnist",
        "stl10",
        "gtsrb",
        "country211",
        "renderedsst2",
        "vtab/caltech101",
        "vtab/cifar10",
        "vtab/cifar100",
        "vtab/clevr_count_all",
        "vtab/clevr_closest_object_distance",
        "vtab/diabetic_retinopathy",
        "vtab/dmlab",
        "vtab/dsprites_label_orientation",
        "vtab/dsprites_label_x_position",
        "vtab/dtd",
        "vtab/eurosat",
        "vtab/kitti_closest_vehicle_distance",
        "vtab/flowers",
        "vtab/pets",
        "vtab/pcam",
        "vtab/resisc45",
        "vtab/smallnorb_label_azimuth",
        "vtab/smallnorb_label_elevation",
        "vtab/svhn",
    ],
    "imagenet": [],
    "huggingfacepics": [
        ['corgi', 'samoyed', 'shiba inu'],
        ['chairs', 'hot dog', 'ice cream', 'ladders', 'tables'],
        ['corgi', 'husky', 'shibu inu'],
        ['alpaca', 'guanaco', 'llama', 'vicuna'],
        ['cotton candy', 'hamburger', 'hot dog', 'nachos', 'popcorn'],
        ['Bacterial_spot', 'Healthy'],
        ['chocolate ice cream', 'vanilla ice cream'],
        ['hot dog', 'not hot dog'],
        ['italy soccer fan', 'spain soccer fan'],
        ['drone', 'fighter', 'uav'],
        ['aragorn', 'frodo', 'gandalf', 'gollum', 'legolas'],
        ['upside_down', 'original'],
        ['golden retriever', 'great dane', 'husky'],
        ['computer mouse', 'desktop', 'keyboard', 'laptop', 'monitor'],
        ['dingo', 'koala', 'kookaburra', 'possum', 'tasmanian devil'],
        ['bathroom', 'bedroom', 'dining room', 'kitchen', 'laundry room', 'living room'],
        ['cake', 'cookie', 'pie'],
        ['automobiles', 'planes', 'trains'],
        ['pasta', 'pizza', 'ravioli'],
        ['cheetah', 'elephant', 'giraffe', 'rhino'],
        ['bagel', 'donut'],
        ['bernese mountain dog', 'husky', 'saint bernard'],
        ['denver', 'new york city', 'paris'],
        ['normal', 'pneumothorax'],
        ['arc de triomphe', 'big ben', 'la sagrada familia', 'leaning tower of pisa', 'taj mahal'],
        ['african pygmy goat', 'nigerian dwarf goat'],
        ['dog drinking water', 'dog eating food', 'dog playing toy', 'dog sleeping'],
        ['apple', 'banana', 'mango', 'orange', 'tomato'],
        ['dosa', 'idli', 'naan', 'samosa', 'vada'],
        ['control', 'flysheet'], ['apple', 'banana', 'grape', 'kiwi', 'lemon'],
        ['bunny', 'moon', 'sun', 'tiger'],
        ['idli', 'kachori', 'pani puri', 'samosa', 'vada pav'],
        ['dosai', 'idiyappam', 'idli', 'puttu', 'vadai'],
        ['Public Drinking', 'Public Smoking', 'non-violation'],
        ['bee', 'hoverfly', 'wasp'],
        ['Beach', 'City', 'Forest'],
        ['bathroom', 'bedroom', 'dining room', 'kitchen', 'living room'],
        ['clover', 'dichondra', 'grass'],
        ['blue whale', 'dolphin', 'orca whale'],
        ['buldog', 'golden', 'pug'],
        ['karanfil', 'leylak', 'menekse', 'nergis', 'zambak'],
        ['London', 'New York', 'Tokyo'],
        ['Husky siberiano', 'cocker spaniel', 'galgo', 'labrador', 'pastor aleman'],
        ['cucumber', 'green beans', 'okra', 'pickle', 'zucinni'],
        ['Big Check shirt', 'Formal Shirt', 'casual shirt', 'denim shirt'],
        ['best kitchen island', 'kitchen cabinet', 'kitchen countertop'],
        ['Bulldog', 'German Shepherd Dog', 'Golden Retriever Dog', 'Shiba Inu Dog'],
        ['Cooling tower', 'Transmission grid', 'Wind turbines'],
        ['dark skin', 'light skin'],
        ['damaged road', 'good road'],
        ['beer', 'wine'],
        ['beer', 'whisky', 'wine'],
        ['classical revival architecture', 'craftsman bungalow architecture', 'mid-century modern ranch', 'queen anne architecture', 'tudor cottage architecture'],
        ['corgi', 'husky', 'samoyed', 'shiba inu'],
    ],
}
